use P_HadoopImp_S;

CREATE MULTISET TABLE P_HadoopImp_S.ShopNPSURL_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
ShopAcctID		varchar(100) CHARACTER SET LATIN NOT CASESPECIFIC,
ShopNPSURL              varchar(100)CHARACTER SET LATIN NOT CASESPECIFIC,
LoadDt                  DATE FORMAT 'yyyy-mm-dd'
)
PRIMARY INDEX nupi_ShopNPSURL_STG ( ShopAcctID );